### ISSUE TITLE
Change default install path, and allow override with user/local config

### ISSUE THREAD

**Issue by saracen** [ProjectBorealis/ue4versionator#1]
Few changes requested from users:

- Default installation engine path should be in the same directory as .ue4versionator config. Users git clone the LFS repository on large drives to accommodate, we shouldn't assume they're okay with large engine installations going to their home directory.
- Some users may want a user/local config to override this default path and a few other settings, such as a setting to always enable debugging symbol downloads.

**Comment by mastercoms** [comment]
Partial solution for now to address immediate user demands committed in https://github.com/ProjectBorealis/ue4versionator/commit/6d8d2d8df3581ba2eebaaae758d9f5dbb4a2e132.

**Comment by saracen** [comment]
I commented on that commit with an alternative, potentially safer, temporary solution.
